name = "MerkabahCY"
uuid = "a1b2c3d4-e5f6-4a5b-bc6d-7e8f9a0b1c2d"
authors = ["Arquiteto <root@arkhe.systems>"]
authors = ["Rafael Oliveira"]
uuid = "ee583c4d-c3c5-4534-a109-ef19be74522e"
authors = ["Rafael Oliveira"]
version = "1.0.0"

[deps]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c523dd2ae4"

[targets]
test = ["Test"]
