name = "MerkabahCY"
uuid = "ee583c4d-c3c5-4534-a109-ef19be74522e"
authors = ["Arquiteto <root@arkhe.systems>"]
version = "1.0.0"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
GraphNeuralNetworks = "cffab07f-9bc2-4db1-8861-388f63bf7694"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"
Test = "8dfed614-e22c-5e08-85e1-65c523dd2ae4"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c523dd2ae4"

[targets]
test = ["Test"]
