[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
GraphNeuralNetworks = "cffab07f-9bc2-4db1-8861-388f63bf7694"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Symbolics = "0c5d862f-8b57-4792-8d23-627444e9da47"
Tullio = "bc48ee85-29a4-5162-ae0b-a64e1601d4bc"
