[package]
name = "arkhe-crds"
version = "0.1.0"
edition = "2021"

[dependencies]
kube = { version = "0.82", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
schemars = "0.8"
